#!/usr/bin/env bash
# Install and configure nginx

sudo apt-get -y update
sudo apt-get -y install nginx

sudo rm -f /var/www/html/*
echo "Hello World!" | sudo tee /var/www/html/index.html
service nginx start
