#!/usr/bin/env bash
# Install and configure nginx

sudo apt-get -y update
sudo apt-get -y install nginx

sudo rm -f /var/www/html/*
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start

NGINX_CONFIG="
server {
	   listen 80 default_server;
	   listen [::]:80 default_server;

       root /var/www/html;

       index index.html index.htm index.nginx-debian.html;

	   error_page 404 /404.html;

       server_name _;

	   location /404.html {
	   			internal;
	   }

       location /redirect_me {
       			return 301 https://www.google.com;
	   }

       location / {
       			try_files \$uri \$uri/ =404;
       }
}
"

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

echo -e "$NGINX_CONFIG" | sudo tee /etc/nginx/sites-enabled/default

sudo service nginx reload
