#!/usr/bin/env bash
# Install and configure nginx

sudo apt-get -y update
sudo apt-get -y install nginx

config="\nadd_header X-Served-By \$hostname;"

sudo sed -i "s/http {/&${config}/" /etc/nginx/nginx.conf

sudo service nginx reload
